---
- hosts: localhost
  gather_facts: true
  become: true
  vars:
    workadventure_domain: "workadventure.localhost"
    workadventure_start_room: "/_/global/raw.githubusercontent.com/raumzeitlabor/rc3-map-lounge/main/main.json"
    jitsi_url: "meet.jit.si"
    jitsi_private_mode: False
    skip_full_upgrade: True
    ansible_become_pass: "{{ local_become_pass }}"
    max_per_group: 5
    max_username_lenght: 25
    admin_api_token: "{{ ansible_fqdn | password_hash('sha512') | password_hash('sha512') }}"
    admin_api_url: "admin.api.{{ workadventure_domain }}"
  tasks:

    - include_role:
        name: user_setup
      loop:
        - "{{ users.<your-user> }}"

    - include_role:
        name: generic_setup
      tags:
        - packages

    - include_role:
        name: security
      tags:
        - security

    - include_role:
        name: docker_setup
      tags:
        - packages

    - include_role:
        name: workadventure_setup
      tags:
        - product

