#!/bin/bash
DEBIAN_FRONTEND=noninteractive apt --assume-yes update
DEBIAN_FRONTEND=noninteractive apt --assume-yes full-upgrade
DEBIAN_FRONTEND=noninteractive apt --assume-yes install git ansible
git clone https://github.com/devnope/ansible-workadventure /opt/ansible-workadventure
sudo reboot
